NThreads: 20
BufferSize: 2
ColumnDict: [ 
              fPtHe3/F,
              fEtaHe3/F,
              fPhiHe3/F,
              fPtHad/F,
              fEtaHad/F,
              fPhiHad/F,
              fDCAxyHe3/F,
              fDCAzHe3/F,
              fDCAxyHad/F,
              fDCAzHad/F,
              fSignalTPCHe3/F,
              fInnerParamTPCHe3/F,
              fSignalTPCHad/F,
              fInnerParamTPCHad/F,
              fNClsTPCHe3/b,
              fNSigmaTPCHe3/F,
              fNSigmaTPCHad/F,
              fChi2TPCHe3/F,
              fChi2TPCHad/F,
              fMassTOFHe3/F,
              fMassTOFHad/F,
              fPIDtrkHe3/i,
              fPIDtrkHad/i,
              fItsClusterSizeHe3/i,
              fItsClusterSizeHad/i,
              fSharedClustersHe3/b,
              fSharedClustersHad/b,
              fIsBkgUS/O,
              fIsBkgEM/O,
              fCollisionId/G,
              fZVertex/F,
              fMultiplicity/F,
              fCentralityFT0C/F,
              fMultiplicityFT0C/F,
            ]
Columns:    [ 
              fPtHe3,
              fEtaHe3,
              fPhiHe3,
              fPtHad,
              fEtaHad,
              fPhiHad,
              fDCAxyHe3,
              fDCAzHe3,
              fDCAxyHad,
              fDCAzHad,
              fSignalTPCHe3,
              fInnerParamTPCHe3,
              fSignalTPCHad,
              fInnerParamTPCHad,
              fNClsTPCHe3,
              fNSigmaTPCHe3,
              fNSigmaTPCHad,
              fChi2TPCHe3,
              fChi2TPCHad,
              fMassTOFHe3,
              fMassTOFHad,
              fPIDtrkHe3,
              fPIDtrkHad,
              fItsClusterSizeHe3,
              fItsClusterSizeHad,
              fSharedClustersHe3,
              fSharedClustersHad,
              fIsBkgUS,
              fIsBkgEM,
              fCollisionId,
              fZVertex,
              fMultiplicity,
              fCentralityFT0C,
              fMultiplicityFT0Ct
            ]
SecondElementColumns: [
              fPtHad,
              fEtaHad,
              fPhiHad,
              fDCAxyHad,
              fDCAzHad,
              fSignalTPCHad,
              fInnerParamTPCHad,
              fNSigmaTPCHad,
              fChi2TPCHad,
              fMassTOFHad,
              fPIDtrkHad,
              fItsClusterSizeHad,
              fSharedClustersHad
            ]
MixingExclusionVariable: fCollisionId

BinVariableX: fCentralityFT0C # centrality - dummy
BinVariableY: fZVertex        # z-vertex - dummy
NbinsX: 10
Xmin: 0.
Xmax: 50.
NbinsY: 20 
Ymin: -10.
Ymax: 10.